

export const Posts = [
    {
        profilePicture: '/Board_images/beeFarm.jpeg',
        farmName: 'משק דבורים דבורי',
        desc: 'דבש דבורים טבעי טהור, מחיר השקה של 50 ש"ח לצנצנת קטנה, 74 ש"ח לצנצנת גדולה',
        posted: "לפני 5 דק'",
        date: '12.5',
        price: ' 50-74 ש"ח',
        location: "משק דבורי, דימונה",
        time: '10:00-17:00',
    },
    {
        profilePicture: '/Board_images/farm1.jpeg',
        farmName: 'משק הגולן',        
        desc: "מביאים אליכם מלפפונים ישר מהשדה, יחד עם יתר הירקות המעולים שגידלנו. משק הגולן- פותחים דוכן חגיגי בבאר שבע. מארז מיני ירקות קטן מתנה ל-100 הקונים הראשונים, בהצגת מודעה זו.",
        photo: '/Board_images/cucumbers.webp',
        posted: "לפני 35 דק'",
        date: " 4.5",
        price: '5-12 ש"ח לק"ג',
        location: ' גרנד קניון באר שבע',
        time: '07:00-14:00',
    },
    {
        profilePicture: '/Board_images/fruitsandvegies.avif',
        farmName: 'Fruits 4 U' ,        
        desc: "מארז פירות מפנק, כולל פירות יבשים. פירוט תכולת המארז: מלון,אבטיח,קיווי,קרמבולה,משמש,תותים,פסיפלורה,ענבים ירוקים,ענבים שחורים. בואו לבקר בדוכן שלנו בקניון חולון",
        photo: '/Board_images/fruits.jpg',
        posted: "לפני שעה",
        date: '1.5',
        price: '  200 ש"ח',
        location: ' קניון חולון',
        time: '10:00-13:00',
    },
    {
        profilePicture: '/Board_images/cheeseFarm.png',
        farmName: 'משק מולדת',        
        desc: 'פלטת גבינות זוגית במבצע לכבוד חג השבועות, 240 ש"ח בלבד, במקום 320 ש"ח. למציג מודעה זו במשק שלנו.',
        photo: '/Board_images/cheese.webp',
        posted: 'לפני 3 שעות', 
        date: " 14.5",
        price: ' 240 ש"ח',
        location: "משק מולדת, חדרה",
        time: '11:00-15:00',
    },
    {
        profilePicture: '/Board_images/farm2.jpg',
        farmName: 'משק ירק ירוק',       
        desc: "מכירת חיסול! מוזמנים להגיע אלינו ולהנות מהירקות המעולים שלנו, לפני שנזרקים עקב חוסר מקום במדפים. המחירים זולים בטירוף!!",
        posted: 'לפני 2 ימים',
        date: '1.5',
        price: ' 4.7-10.5 ש"ח לק"ג',
        location: " משק ירק ירוק, אזור",
        time: '09:00-13:00',
    },
    {
        profilePicture: '/Board_images/farm2.jpg',
        farmName: 'משק ירק ירוק', 
        profilePicture: '/Board_images/farmer1.jpg',
        userName: 'דוד כהן',      
        desc: "עגבניות אורגניות בזיל הזול",
        photo: '/Board_images/fresh_tomatoes.jpg',
        posted: 'לפני 3 ימים',
        date: '20.5',
        price: '  5.9 ש"ח לק"ג',
        location: ' שוק הכרמל, תל אביב',
        time: '11:00-18:00',
    },
]